_target_: lightning.pytorch.trainer.Trainer

min_epochs: 1 # prevents early stopping
max_epochs: 10

accelerator: gpu
devices: [0]

# mixed precision for extra speed-up
precision: 32

# perform a validation loop every N training epochs
check_val_every_n_epoch: 10

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

accumulate_grad_batches: 1
num_sanity_val_steps: 0