# csv logger built in lightning

csv:
  _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
  save_dir: ${paths.root_dir}/logs/${data.data_config.model}_${data.data_config.functional_relationships}_num_nodes_${model.model.num_nodes}_size_${data.data_config.nx}_map_${data.data_config.map_type}_${data.data_config.seed}
  # save_dir: ${paths.root_dir}/logs/${data.data_config.model}_${data.data_config.functional_relationships}_num_nodes_${data.data_config.num_nodes}_size_${data.data_config.nx}_${data.data_config.seed}

  name: "csv/"
