_target_: src.model.ModelTrainer.ModelTrainer

model:
  _target_: src.model.STCD.STCD

  lag: 2
  num_nodes: ${data.data_config.num_nodes}
  nx: ${data.data_config.nx}
  ny: ${data.data_config.ny}
  num_variates: ${data.data_config.num_variates}

  aggregation_function_type: "linear"

  graph_sparsity_factor: 10

  scm_model:
    _target_: src.model.modules.scm.Rhino.Rhino
    decoder:
      _target_: src.model.modules.scm.RhinoSCM.RhinoSCM
      lag: ${model.model.lag}
      num_nodes: ${model.model.num_nodes}
      embedding_dim: 64

    likelihood_model:
      _target_: src.model.modules.scm.likelihood.SplineLikelihood.SplineLikelihood
      num_variates: ${model.model.num_variates}
      nx: ${data.data_config.nx}
      ny: ${data.data_config.ny}
  
  # scm_model:
  #   _target_: src.model.modules.scm.Rhino.Rhino
  #   decoder:
  #     _target_: src.model.modules.scm.LinearDecoder.LinearDecoder
  #     lag: ${model.model.lag}
  #     num_nodes: ${model.model.num_nodes}

  #   likelihood_model:
  #     _target_: src.model.modules.scm.likelihood.MSELikelihood.MSELikelihood
      
training_config:
  _target_: src.auglag.AuglagLRConfig.AuglagLRConfig

  lr_update_lag: 500
  lr_update_lag_best: 500
  lr_init_dict:
    scm: 3e-3
    graph: 3e-3
    aggregation: 1e-3
    mapping: 1e-2

  aggregation_period: 20
  lr_factor: 0.1
  max_lr_down: 3
  penalty_progress_rate: 0.65
  safety_rho: 1e13
  safety_alpha: 1e13
  inner_early_stopping_patience: 1500
  max_outer_steps: 100
  patience_penalty_reached: 100
  patience_max_rho: 3
  penalty_tolerance: 1e-5
  max_inner_steps: 6000
  force_not_converged: false
  init_rho: 1
  init_alpha: 0

# compile model for faster training with pytorch 2.0
compile: false
